version: "3"
services:
  db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - prod.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    env_file:
      - prod.env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    env_file:
      - prod.env
